# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: luengas.dev
email: contact@luengas.dev
description: Personal project site for Henry Luengas
github_username: hluengas
minimal_mistakes_skin: dark
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles

include:
  - _pages

# parse markdown inside block-level HTML tag
# kramdown:
#   parse_block_html: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Henry Luengas"
  avatar : "/assets/media/Headshots/hluengasHeadshotIvy2-cropped.jpg"
  bio    : "I am a technology enthusiast and network engineer at AT&T. I have experience with 5G core networks, software defined networking, container virtualization, systems programming, graphics & rendering, software development processes, and technical support for Linux, Windows, and MacOS."
  links:
    - label:  "GitHub"
      icon:   "fab fa-fw fa-github"
      url:    "https://github.com/hluengas"
    - label:  "LinkedIn"
      icon:   "fab fa-fw fa-linkedin"
      url:    "https://www.linkedin.com/in/henry-luengas"
    - label:  "Email"
      icon:   "fab fa-fw far fa-envelope"
      url:    "mailto:contact@luengas.dev"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hluengas"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/henry-luengas"
    - label:  "Email"
      icon:   "fab fa-fw far fa-envelope"
      url:    "mailto:contact@luengas.dev"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
